version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docekr/nginx/log:/var/log/nginx/
      - ./www:/var/www/html/
    ports:
      - 8080:80
    links:
      - php

  php:
    # image: php-custom:1.0.0
    image: php-custom:3.0.1
    container_name: php
    volumes:
      - ./docker/php/supervisor/supervisord.conf:/etc/supervisord.conf:ro
      - ./www:/var/www/html/

  adminer:
    image: adminer-custom
    container_name: adminer
    volumes:
      - ./docker/adminer/src/adminer-4.8.1.php:/var/www/html/index.php:ro # -- read-only
    ports:
      - 81:80

  # pgsql:
  #   image: postgres:alpine
  #   container_name: pgsql
  #   volumes:
  #       - "./docker-web/data:/var/lib/postgresql/data"
  #   environment:
  #       POSTGRES_USER: foobar
  #       POSTGRES_PASSWORD: foobar
  #       POSTGRES_DB: foobar
