# <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Dcoker Compose - Adminer & Postgres
# 
#  #  Developed by    : LeGrizzly#0341
#  #  Support         : LeGrizzly#0341
#  #  GitHub          : https://github.com/xalsie
#   _                _____          _               _         
#  | |              / ____|        (_)             | |        
#  | |        ___  | |  __   _ __   _   ____  ____ | |  _   _ 
#  | |       / _ \ | | |_ | | \__| | | |_  / |_  / | | | | | |
#  | |____  |  __/ | |__| | | |    | |  / /   / /  | | | |_| |
#  |______|  \___|  \_____| |_|    |_| /___| /___| |_|  \__, |
#                                                        __/ |
#                                                       |___/
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_Update: 13/05/23_~~-->
version: '3.8'

services:
  adminer:      # build ok
    image: legrizzly/adminer-custom:2.0.1
    container_name: adminer
    # build:
    #   context: ./docker/adminer
    #   dockerfile: Dockerfile
    volumes:
      - ./docker/adminer/src/adminer-4.8.1.php:/srv/index.php:ro # -- read-only
    depends_on:
      - postgres
    ports:
      - 81:80
    networks:
      - net-for-back

  postgres:     # build ok
    image: legrizzly/pgsql-custom:1.0.4
    container_name: postgres
    # build:
      # context: ./docker/postgres
      # dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - net-for-back

networks:
  net-for-front:
    name: front-web
  net-for-back:
    name: back-db
